CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "email" varchar(255) UNIQUE,
  "password_hash" varchar(255),
  "role" varchar(50) DEFAULT 'patient',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "consultations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symptoms" text,
  "diagnosis_summary" text,
  "severity" varchar(50),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "symptoms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "category" varchar(100)
);

CREATE TABLE "consultation_symptoms" (
  "consultation_id" int,
  "symptom_id" int,
  "notes" text
);

CREATE TABLE "medicines" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "image_url" varchar(255),
  "description" text,
  "dosage" varchar(100),
  "contraindications" text,
  "is_prescription_required" boolean DEFAULT true
);

CREATE TABLE "medicine_recommendations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultation_id" int,
  "medicine_id" int,
  "reason" text,
  "confidence_score" float
);

CREATE TABLE "ai_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultation_id" int,
  "input_text" text,
  "output_text" text,
  "timestamp" timestamp DEFAULT (now())
);

ALTER TABLE "consultations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "consultation_symptoms" ADD FOREIGN KEY ("consultation_id") REFERENCES "consultations" ("id");

ALTER TABLE "consultation_symptoms" ADD FOREIGN KEY ("symptom_id") REFERENCES "symptoms" ("id");

ALTER TABLE "medicine_recommendations" ADD FOREIGN KEY ("consultation_id") REFERENCES "consultations" ("id");

ALTER TABLE "medicine_recommendations" ADD FOREIGN KEY ("medicine_id") REFERENCES "medicines" ("id");

ALTER TABLE "ai_logs" ADD FOREIGN KEY ("consultation_id") REFERENCES "consultations" ("id");
